workflows:
  macos-workflow:
    name: macOS Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        TERM: xterm-256color
        SHELL: /bin/bash
        FCI_CLONE_DEPTH: 1000
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: frame-callback
          include: true
          source: true
        - pattern: '*'
          include: false
          source: false
    scripts:
      - name: Unpin python - cmake requires the latest version of pinned dependencies
        script: brew unpin python@3.9
      - name: macOS Full Build Script with app-bundle - https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions
        script: ./CI/full-build-macos.sh -b
      - name: ls1
        script: ls -alR /tmp/obsdeps/bin
      - name: ls2
        script: ls -alR /tmp/obsdeps/lib
      - name: ls3
        script: ls -alR build/rundir
    artifacts:
      - build/rundir/RelWithDebInfo/*
      - libobs/**/*.h
      - libobs/**/*.hpp
      - /tmp/obsdeps/*/libavcodec.58.dylib
      - /tmp/obsdeps/*/libavdevice.58.dylib
      - /tmp/obsdeps/*/libavfilter.7.dylib
      - /tmp/obsdeps/*/libavformat.58.dylib
      - /tmp/obsdeps/*/libavutil.56.dylib
      - /tmp/obsdeps/*/libfreetype.6.dylib
      - /tmp/obsdeps/*/libjansson.4.dylib
      - /tmp/obsdeps/*/libluajit-5.1.2.1.0.dylib
      - /tmp/obsdeps/*/libmbedcrypto.2.16.5.dylib
      - /tmp/obsdeps/*/libmbedcrypto.2.24.0.dylib
      - /tmp/obsdeps/*/libmbedcrypto.5.dylib
      - /tmp/obsdeps/*/libmbedtls.2.16.5.dylib
      - /tmp/obsdeps/*/libmbedtls.2.24.0.dylib
      - /tmp/obsdeps/*/libmbedtls.13.dylib
      - /tmp/obsdeps/*/libmbedx509.2.16.5.dylib
      - /tmp/obsdeps/*/libmbedx509.2.24.0.dylib
      - /tmp/obsdeps/*/libmbedx509.1.dylib
      - /tmp/obsdeps/*/libpostproc.55.dylib
      - /tmp/obsdeps/*/librnnoise.0.dylib
      - /tmp/obsdeps/*/libspeexdsp.1.dylib
      - /tmp/obsdeps/*/libswresample.3.dylib
      - /tmp/obsdeps/*/libswscale.5.dylib
      - /tmp/obsdeps/*/libx264.161.dylib
    publishing:
      github_releases:
        prerelease: true
        artifact_patterns:
          - 'build/rundir/RelWithDebInfo/bin/libobs.0.dylib'
      slack:
        channel: '#general'
        notify_on_build_start: true    # To receive a notification when a build starts
        notify:
          success: true                # To not receive a notification when a build succeeds
          failure: true                # To not receive a notification when a build fails
