workflows:
  macos-workflow:
    name: macOS Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        TERM: xterm-256color
        SHELL: /bin/bash
        FCI_CLONE_DEPTH: 1000
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: frame-callback
          include: true
          source: true
        - pattern: '*'
          include: false
          source: false
    scripts:
      - name: Unpin python - cmake requires the latest version of pinned dependencies
        script: brew unpin python@3.9
      - name: macOS Full Build Script - https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions
        script: ./CI/full-build-macos.sh
    artifacts:
      - build/rundir/RelWithDebInfo/*
      - libobs/**/*.h
      - libobs/**/*.hpp
    publishing:
      github_releases:
        prerelease: true
        artifact_patterns:
          - 'build/rundir/RelWithDebInfo/bin/libobs.0.dylib'
      slack:
        channel: '#general'
        notify_on_build_start: true    # To receive a notification when a build starts
        notify:
          success: true                # To not receive a notification when a build succeeds
          failure: true                # To not receive a notification when a build fails
