workflows:
  macos-workflow:
    name: macOS Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        TERM: xterm-256color
        SHELL: /bin/bash
        FCI_CLONE_DEPTH: 1000
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: frame-callback
          include: true
          source: true
    scripts:
      - name: Unpin python - cmake requires the latest version of pinned dependencies
        script: brew unpin python@3.9
      - name: macOS Full Build Script - https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions
        script: ./CI/full-build-macos.sh
    artifacts:
      - build/rundir/RelWithDebInfo/*
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
